<a href="https://colab.research.google.com/github/DaniDotExe/analisis_de_datos/blob/main/Semana_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import pandas as pd
import numpy as np

np.random.seed(42)

n_pacientes = 1000

pacientes = pd.DataFrame({
    "id": np.arange(1, n_pacientes + 1),
    "edad": np.random.randint(18, 90, n_pacientes),
    "peso": np.random.randint(50, 120, n_pacientes),
    "sexo": np.random.choice(["M","F"], n_pacientes),
    "altura_cm": np.random.randint(150, 195, n_pacientes)
})

# -------------------------
# 2. Signos vitales grandes
# cada paciente tiene entre 3 y 10 mediciones
# -------------------------
registros = []

for pid in pacientes["id"]:
    n_med = np.random.randint(3, 11)
    for _ in range(n_med):
        registros.append([
            pid,
            np.random.randint(100, 160),   # presión
            np.random.randint(60, 110),    # fc
            np.random.randint(90, 100),    # spo2
            round(np.random.uniform(36, 39),1)  # temp
        ])

signos = pd.DataFrame(registros, columns=["id","presion","fc","spo2","temp"])

In [ ]:
# -------------------------
# 2. Merge (unir tablas)
# -------------------------
df = pacientes.merge(signos, on="id",how="right")

In [ ]:
df

        id  edad  peso sexo  altura_cm  presion   fc  spo2  temp
0        1    69    56    F        150      112  107    92  38.9
1        1    69    56    F        150      115  102    99  38.4
2        1    69    56    F        150      130   63    96  36.9
3        1    69    56    F        150      121   96    97  36.8
4        1    69    56    F        150      155   62    91  38.5
...    ...   ...   ...  ...        ...      ...  ...   ...   ...
6540  1000    67    51    M        155      144   89    94  37.3
6541  1000    67    51    M        155      137  109    96  37.8
6542  1000    67    51    M        155      141   63    98  37.0
6543  1000    67    51    M        155      111   74    94  38.5
6544  1000    67    51    M        155      157   69    99  36.2

[6545 rows x 9 columns]

In [ ]:
# -------------------------
# 3. Variable derivada
# -------------------------
df["riesgo"] = df["presion"] * df["fc"] / 1000

In [ ]:
df

        id  edad  peso sexo  altura_cm  presion   fc  spo2  temp  riesgo
0        1    69    56    F        150      112  107    92  38.9  11.984
1        1    69    56    F        150      115  102    99  38.4  11.730
2        1    69    56    F        150      130   63    96  36.9   8.190
3        1    69    56    F        150      121   96    97  36.8  11.616
4        1    69    56    F        150      155   62    91  38.5   9.610
...    ...   ...   ...  ...        ...      ...  ...   ...   ...     ...
6540  1000    67    51    M        155      144   89    94  37.3  12.816
6541  1000    67    51    M        155      137  109    96  37.8  14.933
6542  1000    67    51    M        155      141   63    98  37.0   8.883
6543  1000    67    51    M        155      111   74    94  38.5   8.214
6544  1000    67    51    M        155      157   69    99  36.2  10.833

[6545 rows x 10 columns]

In [ ]:
# -------------------------
# 4. Normalización (escala 0–1)
# -------------------------
df["edad_norm"] = (df["edad"] - df["edad"].min()) / (df["edad"].max() - df["edad"].min())

In [ ]:
df

,id,edad,peso,sexo,altura_cm,presion,fc,spo2,temp,riesgo,edad_norm
0,1,69,56,F,150,112,107,92,38.9,11.984,0.718310
1,1,69,56,F,150,115,102,99,38.4,11.730,0.718310
2,1,69,56,F,150,130,63,96,36.9,8.190,0.718310
3,1,69,56,F,150,121,96,97,36.8,11.616,0.718310
4,1,69,56,F,150,155,62,91,38.5,9.610,0.718310
...,...,...,...,...,...,...,...,...,...,...,...
6540,1000,67,51,M,155,144,89,94,37.3,12.816,0.690141
6541,1000,67,51,M,155,137,109,96,37.8,14.933,0.690141
6542,1000,67,51,M,155,141,63,98,37.0,8.883,0.690141
6543,1000,67,51,M,155,111,74,94,38.5,8.214,0.690141
6544,1000,67,51,M,155,157,69,99,36.2,10.833,0.690141

In [ ]:
# -------------------------
# 5. GroupBy (resumen por paciente)
# -------------------------
resumen = df.groupby("id").agg({
    "presion": "mean",
    "fc": "mean",
    "riesgo": "mean"
}).reset_index()

In [ ]:
resumen

       id     presion         fc     riesgo
0       1  130.500000  80.700000  10.429500
1       2  124.600000  82.000000  10.390000
2       3  122.300000  83.400000  10.207400
3       4  126.333333  82.000000  10.406778
4       5  126.800000  84.000000  10.868600
..    ...         ...        ...        ...
995   996  121.333333  83.666667  10.180667
996   997  133.000000  81.888889  10.936889
997   998  121.800000  74.200000   9.098000
998   999  138.000000  75.666667  10.469556
999  1000  135.900000  83.500000  11.317600

[1000 rows x 4 columns]